name: Build examples

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check rust version
        run: rustup show
      - name: Build examples with termion
        run: cargo build --examples --features termion
      - name: Build example with crossterm
        run: cargo build --examples --features crossterm
      - name: Build examples with termion and custom formatter
        run: cargo build --examples --features termion,formatter
