name: Build examples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build examples with tui
      run: cargo build --examples
    - name: Build example with ratatui and termion
      run: cargo build --examples --no-default-features -F ratatui-support,examples-termion 
    - name: Build example with ratatui and crossterm
      run: cargo build --examples --no-default-features -F ratatui-support,examples-crossterm 
